from omnigibson.tasks.task_base import REGISTERED_TASKS
from omnigibson.tasks.dummy_task import DummyTask
from omnigibson.tasks.point_navigation_task import PointNavigationTask
from omnigibson.tasks.point_navigation_obstacle_task import PointNavigationStaticObstacleTask, \
    PointNavigationDynamicObstacleTask
from omnigibson.tasks.point_reaching_task import PointReachingTask
from omnigibson.tasks.furniture_closing_task import FurnitureClosingTask
from omnigibson.tasks.behavior_task import BehaviorTask
