# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: omnigibson.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10omnigibson.proto\"\x1c\n\x0bStepRequest\x12\r\n\x05image\x18\x01 \x02(\x0c\"\x1f\n\x0cStepResponse\x12\x0f\n\x07\x63ommand\x18\x01 \x03(\x02\x32/\n\x06Policy\x12%\n\x04Step\x12\x0c.StepRequest\x1a\r.StepResponse\"\x00')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'omnigibson_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STEPREQUEST']._serialized_start=20
  _globals['_STEPREQUEST']._serialized_end=48
  _globals['_STEPRESPONSE']._serialized_start=50
  _globals['_STEPRESPONSE']._serialized_end=81
  _globals['_POLICY']._serialized_start=83
  _globals['_POLICY']._serialized_end=130
# @@protoc_insertion_point(module_scope)
