from igibson.termination_conditions.termination_condition_base import REGISTERED_TERMINATION_CONDITIONS, \
    REGISTERED_SUCCESS_CONDITIONS, REGISTERED_FAILURE_CONDITIONS, BaseTerminationCondition
from igibson.termination_conditions.falling import Falling
from igibson.termination_conditions.max_collision import MaxCollision
from igibson.termination_conditions.point_goal import PointGoal
from igibson.termination_conditions.predicate_goal import PredicateGoal
from igibson.termination_conditions.reaching_goal import ReachingGoal
from igibson.termination_conditions.timeout import Timeout
