sbatch sample_tasks_sbatch.sh -m restaurant_asian
sbatch sample_tasks_sbatch.sh -m restaurant_brunch
sbatch sample_tasks_sbatch.sh -m restaurant_cafeteria
sbatch sample_tasks_sbatch.sh -m restaurant_diner
sbatch sample_tasks_sbatch.sh -m restaurant_hotel
sbatch sample_tasks_sbatch.sh -m restaurant_urban
sbatch sample_tasks_sbatch.sh -m house_double_floor_lower
sbatch sample_tasks_sbatch.sh -m house_double_floor_upper
sbatch sample_tasks_sbatch.sh -m house_single_floor