#sbatch create_stable_scene_sc.sh -m Beechwood_0_garden
#sbatch create_stable_scene_sc.sh -m Beechwood_0_int
#sbatch create_stable_scene_sc.sh -m Beechwood_1_int
#sbatch create_stable_scene_sc.sh -m Benevolence_0_int
#sbatch create_stable_scene_sc.sh -m Benevolence_1_int
#sbatch create_stable_scene_sc.sh -m Benevolence_2_int
#sbatch create_stable_scene_sc.sh -m Ihlen_0_int
#sbatch create_stable_scene_sc.sh -m Ihlen_1_int
#sbatch create_stable_scene_sc.sh -m Merom_0_garden
#sbatch create_stable_scene_sc.sh -m Merom_0_int
sbatch create_stable_scene_sc.sh -m Merom_1_int
sbatch create_stable_scene_sc.sh -m Pomaria_0_garden
#sbatch create_stable_scene_sc.sh -m Pomaria_0_int
#sbatch create_stable_scene_sc.sh -m Pomaria_1_int
#sbatch create_stable_scene_sc.sh -m Pomaria_2_int
sbatch create_stable_scene_sc.sh -m Rs_garden
#sbatch create_stable_scene_sc.sh -m Rs_int
#sbatch create_stable_scene_sc.sh -m Wainscott_0_garden
#sbatch create_stable_scene_sc.sh -m Wainscott_0_int
#sbatch create_stable_scene_sc.sh -m Wainscott_1_int
#sbatch create_stable_scene_sc.sh -m grocery_store_asian
#sbatch create_stable_scene_sc.sh -m grocery_store_cafe
#sbatch create_stable_scene_sc.sh -m grocery_store_convenience
#sbatch create_stable_scene_sc.sh -m grocery_store_half_stocked
#sbatch create_stable_scene_sc.sh -m hall_arch_wood
#sbatch create_stable_scene_sc.sh -m hall_conference_large
sbatch create_stable_scene_sc.sh -m hall_glass_ceiling
sbatch create_stable_scene_sc.sh -m hall_train_station
sbatch create_stable_scene_sc.sh -m hotel_gym_spa
sbatch create_stable_scene_sc.sh -m hotel_suite_large
sbatch create_stable_scene_sc.sh -m hotel_suite_small
sbatch create_stable_scene_sc.sh -m house_double_floor_lower
sbatch create_stable_scene_sc.sh -m house_double_floor_upper
sbatch create_stable_scene_sc.sh -m house_single_floor
sbatch create_stable_scene_sc.sh -m office_bike
#sbatch create_stable_scene_sc.sh -m office_cubicles_left
#sbatch create_stable_scene_sc.sh -m office_cubicles_right
sbatch create_stable_scene_sc.sh -m office_large
sbatch create_stable_scene_sc.sh -m office_vendor_machine
#sbatch create_stable_scene_sc.sh -m restaurant_asian
#sbatch create_stable_scene_sc.sh -m restaurant_brunch
#sbatch create_stable_scene_sc.sh -m restaurant_cafeteria
sbatch create_stable_scene_sc.sh -m restaurant_diner
#sbatch create_stable_scene_sc.sh -m restaurant_hotel
#sbatch create_stable_scene_sc.sh -m restaurant_urban
#sbatch create_stable_scene_sc.sh -m school_biology
#sbatch create_stable_scene_sc.sh -m school_chemistry
#sbatch create_stable_scene_sc.sh -m school_computer_lab_and_infirmary
#sbatch create_stable_scene_sc.sh -m school_geography
#sbatch create_stable_scene_sc.sh -m school_gym
