#sbatch sample_tasks_sbatch.sh -m Ihlen_0_int
sbatch sample_tasks_sbatch.sh -m Beechwood_0_garden
sbatch sample_tasks_sbatch.sh -m Beechwood_1_int
sbatch sample_tasks_sbatch.sh -m Benevolence_0_int
sbatch sample_tasks_sbatch.sh -m Benevolence_1_int
sbatch sample_tasks_sbatch.sh -m Benevolence_2_int
sbatch sample_tasks_sbatch.sh -m Merom_0_garden
sbatch sample_tasks_sbatch.sh -m Merom_0_int
sbatch sample_tasks_sbatch.sh -m Pomaria_0_garden
sbatch sample_tasks_sbatch.sh -m Pomaria_0_int
sbatch sample_tasks_sbatch.sh -m Pomaria_1_int
sbatch sample_tasks_sbatch.sh -m Pomaria_2_int
sbatch sample_tasks_sbatch.sh -m Rs_garden
sbatch sample_tasks_sbatch.sh -m Wainscott_0_garden
sbatch sample_tasks_sbatch.sh -m Wainscott_1_int
sbatch sample_tasks_sbatch.sh -m grocery_store_asian
