
"""Regenerate the params.yaml file to contain all of the object and scenes."""

import os
import re
import yaml

OBJS_DIR = "../cad/objects"
SCENES_DIR = "../cad/scenes"
OUT_PATH = "../params.yaml"
ROOT_PATH = ".."

DVC_TMPL_PATH = "../dvc-tmpl.yaml"
DVC_OUT_PATH = "../dvc.yaml"

DEP_REGEX = re.compile(r"#\{(.*?)\}")

FINAL_SCENES = [
# "Beechwood_0_int",
# "Beechwood_1_int",
# "Benevolence_0_int",
# "Benevolence_1_int",
# "Benevolence_2_int",
# "Ihlen_0_int",
# "Ihlen_1_int",
# "Merom_0_int",
# "Merom_1_int",
# "Pomaria_0_int",
# "Pomaria_1_int",
# "Pomaria_2_int",
# "Rs_int",
# "Wainscott_0_int",
# "Wainscott_1_int",
# "Beechwood_0_garden",
# "Rs_garden",
# "Pomaria_0_garden",
# "Merom_0_garden",
# "Wainscott_0_garden",
# "house_single_floor",
# "house_double_floor_lower",
# "house_double_floor_upper",
# "grocery_store_asian",
# "grocery_store_cafe",
# "grocery_store_convenience",
# "grocery_store_half_stocked",
# "hall_arch_wood",
# "hall_train_station",
# "hall_glass_ceiling",
# "hall_conference_large",
# "hotel_suite_large",
# "hotel_suite_small",
# "hotel_gym_spa",
# "office_bike",
# "office_cubicles_left",
# "office_cubicles_right",
# "office_large",
# "office_vendor_machine",
# "restaurant_asian",
# "restaurant_cafeteria",
# "restaurant_diner",
# "restaurant_brunch",
# "restaurant_urban",
# "restaurant_hotel",
# "school_gym",
# "school_geography",
# "school_biology",
# "school_chemistry",
# "school_computer_lab_and_infirmary",
]

APPROVED_OBJS = {
    "adhesive-io",
    "air_conditioner-ep",
    "alcohol-ff",
    "allen_wrench-bd",
    "allspice-vw",
    "almond-ab",
    "almond_milk-go",
    "antihistamines-mr",
    "antlers-mq",
    "apple_cider-jf",
    "apple_pie-bk",
    "apron-iu",
    "arugula-lx",
    "asparagus-ew",
    "aspirin-sr",
    "avocado-hz",
    "axe-yy",
    "baby_bottle-hv",
    "baby_monitor-fu",
    "bacon-zi",
    "bait-ec",
    "baking_pan-re",
    "baking_powder-ll",
    "baking_sheet-gz",
    "baking_soda-ni",
    "balloon-km",
    "balsamic_vinegar-cm",
    "bandage-at",
    "bandana-ko",
    "bar_cart-gz",
    "barley-yd",
    "basball_bat-gx",
    "baseball-db",
    "baseball_cap-ul",
    "baseball_glove-cs",
    "bath_mat-he",
    "bath_salt-mo",
    "battery-lb",
    "batting_gloves-nd",
    "bay_leaves-xu",
    "beer_keg-rn",
    "beeswax-ad",
    "birdcage-xo",
    "birdseed-bd",
    "biscuit-vh",
    "black_beans-jm",
    "blackberries-xx",
    "blankets-bx",
    "blazer-fa",
    "blender-temp",
    "blinds-cs",
    "blueberries-dg",
    "blueberry_mousse-ax",
    "boat-qb",
    "bobby_pins-pi",
    "body_srub-vm",
    "body_wash-fd",
    "bolt-oe",
    "boot-ml",
    "bottle-wu",
    "bowling_ball-vx",
    "boxing_gloves-zv",
    "branch-bg",
    "brandy-xw",
    "bread-nx",
    "bread_slice-zj",
    "breadcrumbs-wm",
    "brisket-fi",
    "brown_rice-yb",
    "brownie-xv",
    "brussel_sprouts-zf",
    "bug_repellent-sw",
    "bulb-jv",
    "bun-ae",
    "burlap-sm",
    "burrito-of",
    "buttermilk-ca",
    "butternut_squash-ev",
    "cake-fg",
    "camera-us",
    "candied_yam-jx",
    "candy-mb",
    "canned_beans-nn",
    "canner-fk",
    "canvas-ts",
    "cappuccino-hi",
    "cardigan-xm",
    "cardstock-wi",
    "care_products-gt",
    "cat_food-eg",
    "cauliflower-oy",
    "cell_phone-nb",
    "cellophane-ul",
    "ceramic_tile-yb",
    "ceramic_tile-yr",
    "chalk-ic",
    "champagne_flute-pb",
    "charcoal-vc",
    "charcoal_grill-yf",
    "chard-zo",
    "cheese_danish-jm",
    "cherry_tomato-wq",
    "chicken_breast-zh",
    "chicken_coop-nn",
    "chicken_leg-kc",
    "chicken_thigh-bq",
    "chicken_wing-ye",
    "china-mi",
    "chisel-ls",
    "chocolate_cake-yw",
    "chocolate_chip-qm",
    "chocolate_syrup-eh",
    "chorizo-su",
    "chowder-pu",
    "cigarette-te",
    "cinnamon_stick-jl",
    "citrus-ln",
    "clamp-ok",
    "clip-vb",
    "clock-wy",
    "clothesline-jc",
    "cloves-kp",
    "cocoa_powder-vg",
    "coconut_milk-oq",
    "coconut_oil-xw",
    "coffee-li",
    "coffee_grinder-ag",
    "coke_bottle-al",
    "comic_book-lr",
    "compost_bin-fh",
    "cooler-ac",
    "corkscrew-pa",
    "corn-ds",
    "cotton_balls-ps",
    "cracker-fg",
    "crawfish-bo",
    "crayons-ew",
    "credit_card-nl",
    "crystal-ms",
    "curtain-fh",
    "curtain_rod-la",
    "cymbal-kq",
    "dehumidifier-rw",
    "denture-hi",
    "deodorant-ls",
    "diamond-jh",
    "dice-wq",
    "dish_soap-vr",
    "dish_towel-bv",
    "dough-qd",
    "dowel-ty",
    "dreidel-fe",
    "dried_apricot-fd",
    "dried_cranberries-wt",
    "dried_herb-sl",
    "drying_rack-kc",
    "duck-dg",
    "dutch_oven-wa",
    "easter_egg-kx",
    "eyeshadow-ca",
    "fabric_softener-od",
    "feather-we",
    "fennel-lg",
    "fertilizer_bag-oa",
    "firework-dg",
    "fishing_rod-gz",
    "flag_pole-ee",
    "flask-fu",
    "food_coloring-jw",
    "food_processor-ht",
    "french_press-hq",
    "fuel-pj",
    "garlic-lh",
    "gazpacho-er",
    "gift-sd",
    "gift_bag-ue",
    "goalkeeper_gloves-rk",
    "goblet-zz",
    "goggles-pw",
    "golf_club-aw",
    "granola_bar-le",
    "grapefruit-jg",
    "grass-fg",
    "gravel-wq",
    "green_bean-yr",
    "green_tea-na",
    "grocery_bag-dz",
    "ground_beef",
    "hand_rake-af",
    "hand_sanitizer-ad",
    "haystack-ud",
    "hazelnut-jw",
    "headstone-oq",
    "hockey_puck-jk",
    "hockey_stick-ja",
    "hoe-lg",
    "hot_chocolate-ni",
    "hotdog_sandwitch-as",
    "hutch-cr",
    "ice_bucket-kz",
    "ice_cream-re",
    "ice_cubes",
    "inhaler-rv",
    "ink-pa",
    "iron_board-jq",
    "jacket-ql",
    "jade_roller-fc",
    "jelly_jars-jo",
    "jersey-of",
    "jewelry_cleaner-bh",
    "juicer-gs",
    "kale-sl",
    "kayak-dr",
    "keys-lx",
    "knife-rg",
    "lawnmower-rh",
    "legacy_almond_acooui",
    "legacy_apple_agveuv",
    "legacy_apple_omzprq",
    "legacy_apple_qusmpx",
    "legacy_apple_sguztn",
    "legacy_apricot_inxcvi",
    "legacy_apricot_qmwmwm",
    "legacy_armchair_cyvmhv",
    "legacy_armchair_fsrprw",
    "legacy_armchair_jmunen",
    "legacy_armchair_qgcjtr",
    "legacy_armchair_qjwuus",
    "legacy_armchair_qplklw",
    "legacy_armchair_rabzuf",
    "legacy_armchair_tcxiue",
    "legacy_armchair_umbrpd",
    "legacy_armchair_viphen",
    "legacy_armchair_vtsoat",
    "legacy_armchair_vzhxuf",
    "legacy_armchair_xkacfd",
    "legacy_artichoke_tfclmg",
    "legacy_atomizer_tehmzy",
    "legacy_backpack_gvbiwl",
    "legacy_bagel_zlxkry",
    "legacy_baguette_xydhpd",
    "legacy_ball_nofzds",
    "legacy_banana_vvyyyv",
    "legacy_baseboard_prytbo",
    "legacy_basket_clziqw",
    "legacy_basket_haewxp",
    "legacy_basket_pgwdlg",
    "legacy_basket_pqzyxx",
    "legacy_basket_wdsnjy",
    "legacy_basket_wqxrbf",
    "legacy_basket_xjftlf",
    "legacy_bath_towel_feojdm",
    "legacy_bath_towel_iviyls",
    "legacy_bath_towel_lyqgnf",
    "legacy_bathtub_azdgtl",
    "legacy_bathtub_enpxbn",
    "legacy_bathtub_fdjykf",
    "legacy_bathtub_gulceo",
    "legacy_bathtub_jfhrwj",
    "legacy_bathtub_oobbwn",
    "legacy_bathtub_wxrafq",
    "legacy_bean_cdinsu",
    "legacy_bean_dyjvwv",
    "legacy_bean_lvbjws",
    "legacy_bean_mfkwzi",
    "legacy_bed_pqptex",
    "legacy_bed_sztpse",
    "legacy_beef_vdfkby",
    "legacy_beer_phdimo",
    "legacy_beet_wantjv",
    "legacy_bell_oshurh",
    "legacy_bell_pepper_ggurxn",
    "legacy_bell_pepper_ihctxa",
    "legacy_bell_pepper_ukkycp",
    "legacy_bell_pepper_uqcenz",
    "legacy_bench_hezgut",
    "legacy_bench_jaklov",
    "legacy_bench_nokayw",
    "legacy_bench_nzsfrw",
    "legacy_bench_svnyht",
    "legacy_bench_wtkahs",
    "legacy_blender_eyedvd",
    "legacy_board_game_eoywpy",
    "legacy_board_game_frgdqh",
    "legacy_board_game_fzyuip",
    "legacy_board_game_gcfkqa",
    "legacy_board_game_gumkqh",
    "legacy_board_game_ibzhzu",
    "legacy_board_game_iqfvfl",
    "legacy_board_game_lzslbu",
    "legacy_board_game_nfewft",
    "legacy_board_game_ovttum",
    "legacy_board_game_phwwnx",
    "legacy_board_game_qdkyzl",
    "legacy_board_game_qgvsnb",
    "legacy_board_game_rgvkmy",
    "legacy_board_game_twkglv",
    "legacy_board_game_vbamua",
    "legacy_bow_fhchql",
    "legacy_bowl_ajzltc",
    "legacy_bowl_dalyim",
    "legacy_bowl_eipwho",
    "legacy_bowl_fiarri",
    "legacy_bowl_fwdfeg",
    "legacy_bowl_jfvjep",
    "legacy_bowl_kthvrl",
    "legacy_bowl_mspdar",
    "legacy_bowl_oyidja",
    "legacy_bowl_rlwpcd",
    "legacy_bowl_xpnlup",
    "legacy_bowl_zwhewa",
    "legacy_bracelet_thqqmo",
    "legacy_breakfast_table_bmnubh",
    "legacy_breakfast_table_cjjayg",
    "legacy_breakfast_table_dnsjnv",
    "legacy_breakfast_table_hggsao",
    "legacy_breakfast_table_idnnmz",
    "legacy_breakfast_table_ixvmic",
    "legacy_breakfast_table_kpwegp",
    "legacy_breakfast_table_kwmfdg",
    "legacy_breakfast_table_lcsizg",
    "legacy_breakfast_table_lnwggc",
    "legacy_breakfast_table_lwtcfh",
    "legacy_breakfast_table_metubv",
    "legacy_breakfast_table_mwsyqb",
    "legacy_breakfast_table_pllvrt",
    "legacy_breakfast_table_sfxqtk",
    "legacy_breakfast_table_skseyx",
    "legacy_breakfast_table_uhrsex",
    "legacy_breakfast_table_wwsikw",
    "legacy_breakfast_table_zypvuv",
    "legacy_briefcase_lwbctq",
    "legacy_bucket_bdhvnt",
    "legacy_bucket_lsmlzi",
    "legacy_bucket_wlilma",
    "legacy_bulldog_clip_cqxnkn",
    "legacy_bulletin_board_ayaoal",
    "legacy_bulletin_board_rjlpsy",
    "legacy_butter_ovirmc",
    "legacy_calculator_kwmmty",
    "legacy_caliper_sngjmj",
    "legacy_candle_bhaqam",
    "legacy_candy_cane_qfomjj",
    "legacy_canned_food_acgdtc",
    "legacy_canned_food_cbmndg",
    "legacy_canned_food_foetdd",
    "legacy_canned_food_mzoaia",
    "legacy_canned_food_pkopdw",
    "legacy_canned_food_zfmfje",
    "legacy_cantaloup_pqcnoc",
    "legacy_carafe_ocjcgp",
    "legacy_carpet_ctclvd",
    "legacy_carrot_qhmmmx",
    "legacy_casserole_mmbavt",
    "legacy_catsup_hvxkso",
    "legacy_cauldron_zndohl",
    "legacy_cereal_dkhgxn",
    "legacy_cereal_hcwbzw",
    "legacy_cereal_iucshm",
    "legacy_cereal_surzft",
    "legacy_cereal_tiykku",
    "legacy_chaise_longue_ajjxcd",
    "legacy_chaise_longue_xmjcle",
    "legacy_cheese_hwxeto",
    "legacy_cherry_lkltpa",
    "legacy_chestnut_fmomat",
    "legacy_chestnut_jvnilh",
    "legacy_chestnut_tfawre",
    "legacy_chicken_nppsmz",
    "legacy_chili_nidjog",
    "legacy_chili_pbbkpz",
    "legacy_chip_qstxpj",
    "legacy_chives_gboofh",
    "legacy_chives_vvacxt",
    "legacy_chives_yifjct",
    "legacy_chocolate_box_bdvkbh",
    "legacy_chopping_board_akgegh",
    "legacy_chopping_board_ayegwd",
    "legacy_chopping_board_ktxcvz",
    "legacy_chopping_board_mwmzzv",
    "legacy_chopstick_ahmhza",
    "legacy_cinnamon_bmbjdf",
    "legacy_clout_nail_gvfevt",
    "legacy_clove_thigpl",
    "legacy_coat_brebdk",
    "legacy_coat_kiiium",
    "legacy_coatrack_qyjssf",
    "legacy_coffee_cup_skamgp",
    "legacy_coffee_pouch_fovxcx",
    "legacy_coffee_pouch_zmadza",
    "legacy_coffee_table_aoojzy",
    "legacy_coffee_table_gpkbiw",
    "legacy_coffee_table_hmwkkt",
    "legacy_coffee_table_stocuk",
    "legacy_coffee_table_tzmkgq",
    "legacy_coffee_table_vcgabn",
    "legacy_coffee_table_xshzms",
    "legacy_coffee_table_ytlgdt",
    "legacy_coffee_table_zzqwse",
    "legacy_colander_ambnzk",
    "legacy_cologne_lyipur",
    "legacy_comb_lqnwhb",
    "legacy_conditioner_njqnuo",
    "legacy_console_table_emeeke",
    "legacy_console_table_fihyuz",
    "legacy_console_table_tvhett",
    "legacy_console_table_xqlxni",
    "legacy_container_date_qqddba",
    "legacy_cookie_ggpang",
    "legacy_cord_aqikou",
    "legacy_cord_tzurlz",
    "legacy_cord_ydrhwh",
    "legacy_countertop_tpuwys",
    "legacy_cpu_board_xlqvil",
    "legacy_crab_tjkiva",
    "legacy_cracker_box_cmdigf",
    "legacy_cream_ompiss",
    "legacy_cream_pitcher_wmkwhg",
    "legacy_cruet_njqmqv",
    "legacy_crumb_irhmll",
    "legacy_cucumber_wcvwye",
    "legacy_cup_ckkwmj",
    "legacy_cup_dkxddg",
    "legacy_cup_rypdvd",
    "legacy_cup_vckahe",
    "legacy_cup_ykuftq",
    "legacy_cupcake_pfwrlq",
    "legacy_dart_hzvuwy",
    "legacy_dartboard_zjenlc",
    "legacy_dental_floss_aokqke",
    "legacy_desk_ampuyz",
    "legacy_desk_bptvoy",
    "legacy_desk_clenrz",
    "legacy_desk_cnewsu",
    "legacy_desk_egzdgz",
    "legacy_desk_jfhurf",
    "legacy_desk_kmmlna",
    "legacy_desk_ntezkg",
    "legacy_desk_phavlj",
    "legacy_desk_sfstso",
    "legacy_desk_tdhgko",
    "legacy_desk_tmukzm",
    "legacy_desk_uffjvo",
    "legacy_desk_uxgyui",
    "legacy_desk_vpwmkm",
    "legacy_desk_yezrwt",
    "legacy_desk_zjbhgq",
    "legacy_detergent_gkpmii",
    "legacy_detergent_qjkmhq",
    "legacy_digital_scale_ccphiu",
    "legacy_dinner_napkin_rpccls",
    "legacy_dipper_hqqjfo",
    "legacy_dish_rack_kxuutl",
    "legacy_dishtowel_dtfspn",
    "legacy_dishtowel_ltydgg",
    "legacy_dishtowel_qvzbjx",
    "legacy_dishtowel_yobhae",
    "legacy_document_qkrlsi",
    "legacy_dress_gtghon",
    "legacy_drill_nzgmza",
    "legacy_drumstick_lkvzmj",
    "legacy_duffel_bag_ozykxk",
    "legacy_dustpan_espzwv",
    "legacy_egg_mimzbz",
    "legacy_eggplant_jniuxf",
    "legacy_envelope_urcigc",
    "legacy_eraser_cungod",
    "legacy_fillet_fqhuey",
    "legacy_fish_qofuoa",
    "legacy_floor_lamp_jcbvfi",
    "legacy_floor_lamp_pfuqec",
    "legacy_floor_lamp_vdxlda",
    "legacy_flour_ylezpk",
    "legacy_folder_piezyg",
    "legacy_folderal_ttldpx",
    "legacy_folding_chair_vngcqu",
    "legacy_foot_rule_ckywbx",
    "legacy_foot_rule_rutqab",
    "legacy_foot_rule_swlgkg",
    "legacy_foot_rule_ujizkx",
    "legacy_foot_rule_vmnaih",
    "legacy_frying_pan_sfbdjn",
    "legacy_gaming_table_ipdvzo",
    "legacy_ginger_wqcasl",
    "legacy_gingerbread_hxkcxs",
    "legacy_glass_nfoydb",
    "legacy_glass_slscza",
    "legacy_glove_crbvcg",
    "legacy_glove_hsaxtc",
    "legacy_glove_rlzvry",
    "legacy_gooseberry_cltzwx",
    "legacy_grandfather_clock_icznug",
    "legacy_grandfather_clock_oskfvo",
    "legacy_grape_snjrhg",
    "legacy_grape_uprbwp",
    "legacy_grape_venbog",
    "legacy_grater_jlkowf",
    "legacy_green_onion_chopped_akrkjr",
    "legacy_green_onion_wzqhsg",
    "legacy_griddle_ryvqep",
    "legacy_grill_ddlqye",
    "legacy_guacamole_ajnjvv",
    "legacy_guitar_cybisc",
    "legacy_guitar_gysapt",
    "legacy_guitar_hpqjrq",
    "legacy_guitar_wjohag",
    "legacy_gym_shoe_arigtn",
    "legacy_gym_shoe_hwrvmy",
    "legacy_gym_shoe_kmcbym",
    "legacy_gym_shoe_lqzooz",
    "legacy_gym_shoe_mjyyda",
    "legacy_gym_shoe_pblxfp",
    "legacy_gym_shoe_picdro",
    "legacy_gym_shoe_qxecbh",
    "legacy_gym_shoe_uuvwev",
    "legacy_gym_shoe_wfmrpw",
    "legacy_hairbrush_bdylnb",
    "legacy_hamburger_fyswch",
    "legacy_hammer_bbzlel",
    "legacy_hand_towel_jaubic",
    "legacy_hanger_ffecvd",
    "legacy_hard_drive_ijibkm",
    "legacy_hard_drive_ubjbsm",
    "legacy_hardback_nubbfj",
    "legacy_hat_avvknr",
    "legacy_hat_ldxyyc",
    "legacy_hat_wkrzep",
    "legacy_hat_zymxgw",
    "legacy_head_cabbage_tqohvs",
    "legacy_headset_oytuam",
    "legacy_heater_arfdpk",
    "legacy_heater_dwmloz",
    "legacy_heater_wntwxx",
    "legacy_highchair_eteuuf",
    "legacy_highchair_pahqnp",
    "legacy_highlighter_tcsmqv",
    "legacy_hinge_qroify",
    "legacy_honing_steel_ugerym",
    "legacy_hook_mdnfjr",
    "legacy_hose_gavrvw",
    "legacy_ice_cube_iiimgo",
    "legacy_ink_cartridge_ltblou",
    "legacy_ink_cartridge_oepuip",
    "legacy_ink_cartridge_oinelo",
    "legacy_iron_fzbvce",
    "legacy_jam_vxjbjf",
    "legacy_jar_fyfahz",
    "legacy_jar_gtnmis",
    "legacy_jar_irqkdw",
    "legacy_jar_jbhdeu",
    "legacy_jar_lnxzuy",
    "legacy_jar_nzcbda",
    "legacy_jar_piemou",
    "legacy_jar_pluujx",
    "legacy_jar_qzwijs",
    "legacy_jar_rdngsc",
    "legacy_jar_sktwfj",
    "legacy_jar_uydvnv",
    "legacy_jar_vuolos",
    "legacy_jar_wvgsqk",
    "legacy_jar_xebmcy",
    "legacy_jar_xrirkq",
    "legacy_jar_ykrdzg",
    "legacy_jar_zqoboc",
    "legacy_jeans_nmvvil",
    "legacy_jeans_pvzxyp",
    "legacy_jewel_syneus",
    "legacy_juice_bbewjo",
    "legacy_kettle_bzisss",
    "legacy_kettle_tsyims",
    "legacy_kettle_tzbnmh",
    "legacy_kettle_vjbldp",
    "legacy_keyboard_nddmmy",
    "legacy_kitchen_analog_scale_lpjpez",
    "legacy_kitchen_analog_scale_zpmpoq",
    "legacy_ladder_shfvtl",
    "legacy_lasagna_eovigz",
    "legacy_lawn_mower_bterwo",
    "legacy_lemon_vuwehu",
    "legacy_lemon_wouoym",
    "legacy_lettuce_yxemcs",
    "legacy_lid_aybgkm",
    "legacy_lid_chwwdg",
    "legacy_lid_dkncbi",
    "legacy_lid_exiqxa",
    "legacy_lid_exzfzm",
    "legacy_lid_fnqhbz",
    "legacy_lid_haxrqc",
    "legacy_lid_itwwle",
    "legacy_lid_jqvurl",
    "legacy_lid_jvqtqi",
    "legacy_lid_jvzjzp",
    "legacy_lid_lwyfab",
    "legacy_lid_muczdt",
    "legacy_lid_niarsj",
    "legacy_lid_qferch",
    "legacy_lid_qfqccp",
    "legacy_lid_qhlsdq",
    "legacy_lid_qkogll",
    "legacy_lid_utfcdx",
    "legacy_lid_uwzqlf",
    "legacy_lid_vkepll",
    "legacy_light_bulb_kfmkwd",
    "legacy_lime_iwjcjp",
    "legacy_lipstick_petufo",
    "legacy_lollipop_bhjyff",
    "legacy_lotion_ixfuxm",
    "legacy_loudspeaker_avtlcj",
    "legacy_loudspeaker_bmpdyv",
    "legacy_magazine_ehdwsd",
    "legacy_martini_xevdnl",
    "legacy_mat_mayaur",
    "legacy_mayonnaise_ktmjvg",
    "legacy_medicine_egondf",
    "legacy_medicine_fmfwng",
    "legacy_medicine_hvocpc",
    "legacy_medicine_kasbsy",
    "legacy_medicine_kqkwoq",
    "legacy_medicine_qqsukh",
    "legacy_medicine_syfpak",
    "legacy_medicine_zfbnjh",
    "legacy_milk_xbvdpc",
    "legacy_mirror_pevdqu",
    "legacy_monitor_huvcgu",
    "legacy_monitor_rbqanz",
    "legacy_mouse_oydobn",
    "legacy_mousetrap_mwfwsv",
    "legacy_muffin_pxrntz",
    "legacy_mug_ppzttc",
    "legacy_mushroom_xeodai",
    "legacy_mushroom_zlukhz",
    "legacy_necklace_wzmleo",
    "legacy_newspaper_ukamcl",
    "legacy_notebook_aanuhi",
    "legacy_notebook_ffdjzp",
    "legacy_notebook_jxabmj",
    "legacy_notebook_ksxknp",
    "legacy_notebook_umxsmd",
    "legacy_notebook_xhigou",
    "legacy_oatmeal_zkggxm",
    "legacy_olive_oil_cqycjk",
    "legacy_olive_oil_luikop",
    "legacy_olive_oil_lvsfgc",
    "legacy_olive_rstwkd",
    "legacy_olive_rzktwr",
    "legacy_orange_ucstpm",
    "legacy_orange_yloghd",
    "legacy_package_sxlklf",
    "legacy_paint_gjjugj",
    "legacy_paint_mxyrzd",
    "legacy_paint_qbqche",
    "legacy_paint_ycnaho",
    "legacy_paintbrush_gngyrk",
    "legacy_painting_ggloob",
    "legacy_painting_uzhuyu",
    "legacy_pajamas_rcgdde",
    "legacy_paper_bag_bzsxgw",
    "legacy_paper_clip_xjfirk",
    "legacy_paper_towel_aclaus",
    "legacy_paper_towel_holder_rntefx",
    "legacy_parsley_kkgkkd",
    "legacy_pasta_gwqhko",
    "legacy_pea_iblyep",
    "legacy_peach_orowgl",
    "legacy_peach_wrutgk",
    "legacy_pear_mqvgcg",
    "legacy_pear_ngtwvy",
    "legacy_pedestal_table_ktevfe",
    "legacy_pedestal_table_mbojpo",
    "legacy_pedestal_table_oqclwq",
    "legacy_pedestal_table_poukwl",
    "legacy_pegboard_jafivf",
    "legacy_pen_nqxveo",
    "legacy_pen_zmimhb",
    "legacy_pencil_box_acikzo",
    "legacy_pencil_box_otcmih",
    "legacy_pencil_dcqvto",
    "legacy_pencil_faudjj",
    "legacy_pencil_lrwosa",
    "legacy_pencil_tqrrbk",
    "legacy_pencil_vakowb",
    "legacy_pencil_xuanpj",
    "legacy_pencil_zzzvln",
    "legacy_pepper_grinder_tfoogy",
    "legacy_perfume_ipurzb",
    "legacy_piano_bnxcvw",
    "legacy_piano_ojoiqt",
    "legacy_piano_ygmqqa",
    "legacy_picture_cltbty",
    "legacy_picture_etixod",
    "legacy_picture_fanvpf",
    "legacy_picture_fhkzlm",
    "legacy_picture_gwricv",
    "legacy_picture_hhxttu",
    "legacy_picture_jpfyrq",
    "legacy_picture_lucjyq",
    "legacy_picture_qavxsz",
    "legacy_picture_qjkajj",
    "legacy_picture_qtvjzk",
    "legacy_picture_rciuob",
    "legacy_picture_szpupz",
    "legacy_picture_tlwjpv",
    "legacy_picture_weqggl",
    "legacy_picture_wfdvzv",
    "legacy_picture_yrgaal",
    "legacy_picture_ytxhyl",
    "legacy_picture_zsirgc",
    "legacy_pillow_ajpapo",
    "legacy_pillow_fxxpwf",
    "legacy_pillow_pjqqmb",
    "legacy_pillow_rteuzs",
    "legacy_pillow_tepkbl",
    "legacy_pillow_uavnng",
    "legacy_pineapple_jizmyh",
    "legacy_pineapple_wfaybl",
    "legacy_pineapple_zympwt",
    "legacy_pistachio_bhirar",
    "legacy_plate_iawoof",
    "legacy_platter_csanbr",
    "legacy_platter_ekjpdj",
    "legacy_platter_hnlivs",
    "legacy_platter_iadlti",
    "legacy_platter_kiiamx",
    "legacy_plum_dsybez",
    "legacy_plum_rhaemq",
    "legacy_plywood_fkmkqa",
    "legacy_pomegranate_tbwsgm",
    "legacy_pomegranate_tldskr",
    "legacy_pomegranate_vqybii",
    "legacy_pomelo_ezckjt",
    "legacy_pomelo_qecwzm",
    "legacy_pool_xixlzr",
    "legacy_pop_bqretx",
    "legacy_pop_case_dufbnv",
    "legacy_pop_case_gwgaqb",
    "legacy_pop_case_noiyxv",
    "legacy_pop_case_oarbks",
    "legacy_pop_case_pldtgy",
    "legacy_pop_case_qcfxec",
    "legacy_pop_case_qwtbon",
    "legacy_pop_case_rzhvvk",
    "legacy_pop_case_seiatm",
    "legacy_pop_case_sqiatv",
    "legacy_pop_case_unmexe",
    "legacy_pop_case_zfyatg",
    "legacy_pop_case_zxguap",
    "legacy_pop_chwjfu",
    "legacy_pop_dlqmit",
    "legacy_pop_drqbiy",
    "legacy_pop_exapzb",
    "legacy_pop_ghxeqz",
    "legacy_pop_haoywb",
    "legacy_pop_hjrwqb",
    "legacy_pop_iloapr",
    "legacy_pop_jnoksl",
    "legacy_pop_kviogj",
    "legacy_pop_mdznsn",
    "legacy_pop_mhzttm",
    "legacy_pop_mrrozu",
    "legacy_pop_msmlud",
    "legacy_pop_nepfjl",
    "legacy_pop_nyupqh",
    "legacy_pop_oeipjl",
    "legacy_pop_oghrnk",
    "legacy_pop_pfjzkn",
    "legacy_pop_pvabxf",
    "legacy_pop_pyrics",
    "legacy_pop_rhclfg",
    "legacy_pop_ribekf",
    "legacy_pop_sevoto",
    "legacy_pop_ubazru",
    "legacy_pop_uwmchl",
    "legacy_pop_uzbpnw",
    "legacy_pop_vfjhav",
    "legacy_pop_vszbvb",
    "legacy_pop_wmqhul",
    "legacy_pop_wrgmdt",
    "legacy_pop_xlyult",
    "legacy_pop_xoldze",
    "legacy_pop_zxambx",
    "legacy_pork_ihekpm",
    "legacy_pot_plant_azfbnd",
    "legacy_pot_plant_imhfnc",
    "legacy_pot_plant_jaunqh",
    "legacy_pot_plant_kjnypo",
    "legacy_pot_plant_kxmvco",
    "legacy_pot_plant_qbnaph",
    "legacy_pot_plant_qcpges",
    "legacy_pot_plant_qenqqv",
    "legacy_pot_plant_quaxmw",
    "legacy_pot_plant_udqjui",
    "legacy_pot_plant_xlylfy",
    "legacy_pot_plant_yvuagy",
    "legacy_potato_bpwohr",
    "legacy_potato_ljfitc",
    "legacy_potato_lqjear",
    "legacy_potato_ngjeog",
    "legacy_powder_bottle_vfabau",
    "legacy_pretzel_rmutwn",
    "legacy_prosciutto_udjqae",
    "legacy_protein_powder_rbvrrp",
    "legacy_protein_powder_rikjwx",
    "legacy_protein_powder_tpcsve",
    "legacy_protein_powder_ysgesq",
    "legacy_pumpkin_apitmi",
    "legacy_pumpkin_mrntpd",
    "legacy_puree_raagvm",
    "legacy_radish_bpmjki",
    "legacy_radish_vztgpr",
    "legacy_rag_dgzewy",
    "legacy_rag_zmmbpz",
    "legacy_rail_fence_iduxiv",
    "legacy_rail_fence_qmsnld",
    "legacy_rail_fence_vwpqly",
    "legacy_rake_jjetot",
    "legacy_range_hood_duqgcu",
    "legacy_range_hood_iqbpie",
    "legacy_range_hood_lejkwg",
    "legacy_range_hood_ylsdmp",
    "legacy_raspberry_spkers",
    "legacy_razor_jocsgp",
    "legacy_rib_nzbnqp",
    "legacy_ribbon_puwdwq",
    "legacy_ring_oolbrj",
    "legacy_rocking_chair_drpbxj",
    "legacy_roller_jcqwrt",
    "legacy_rosehip_xembcb",
    "legacy_router_dsgtpk",
    "legacy_salad_dhdhul",
    "legacy_salt_iomwtn",
    "legacy_sandal_chgcrm",
    "legacy_sandal_shdahi",
    "legacy_sandal_spcddb",
    "legacy_sandal_uhzfis",
    "legacy_sandal_zafskl",
    "legacy_saucepan_fsinsu",
    "legacy_sausage_qijvmi",
    "legacy_saw_laysom",
    "legacy_scarf_gqzivs",
    "legacy_scarf_xdcrfh",
    "legacy_scissors_hqfure",
    "legacy_scissors_iizidc",
    "legacy_screwdriver_irtslw",
    "legacy_screwdriver_uajlga",
    "legacy_shampoo_bclpiq",
    "legacy_shampoo_dvrzmy",
    "legacy_shampoo_hlkpwd",
    "legacy_shampoo_jccyom",
    "legacy_shampoo_kkbhzw",
    "legacy_shampoo_nijidu",
    "legacy_shampoo_tzghev",
    "legacy_sheet_czdhwu",
    "legacy_shelf_cqcoox",
    "legacy_shelf_eyidvz",
    "legacy_shelf_lbbims",
    "legacy_shelf_owvfik",
    "legacy_shelf_pkgbcp",
    "legacy_shelf_ptxdid",
    "legacy_shelf_tahafx",
    "legacy_shelf_uriudf",
    "legacy_shelf_vehhll",
    "legacy_shelf_wnvxme",
    "legacy_shoulder_bag_mcualj",
    "legacy_shower_aktzdp",
    "legacy_shower_atiuco",
    "legacy_shower_invgma",
    "legacy_soap_ozifwa",
    "legacy_sock_rhgweu",
    "legacy_sofa_ctjgcl",
    "legacy_sofa_jhfkdc",
    "legacy_sofa_mnfbbh",
    "legacy_sofa_ocydlq",
    "legacy_sofa_rxtscm",
    "legacy_soup_ladle_hgvzdm",
    "legacy_soup_ladle_xocqxg",
    "legacy_soup_wbqjbt",
    "legacy_spaghetti_sauce_zahyds",
    "legacy_spatula_ktkigm",
    "legacy_speaker_system_lgkhqt",
    "legacy_speaker_system_snbvop",
    "legacy_speaker_system_suzqfe",
    "legacy_spinach_nshkpm",
    "legacy_spoon_aeubta",
    "legacy_spoon_huudhe",
    "legacy_spoon_kwyoqh",
    "legacy_spoon_nxddfp",
    "legacy_spoon_prbhag",
    "legacy_spoon_pxwpuw",
    "legacy_spoon_qdepdj",
    "legacy_stand_geeldi",
    "legacy_stand_kanola",
    "legacy_stand_ljtrka",
    "legacy_standing_tv_bkyguk",
    "legacy_standing_tv_blyapt",
    "legacy_standing_tv_ghxsoy",
    "legacy_standing_tv_gjlztf",
    "legacy_standing_tv_lkpsai",
    "legacy_standing_tv_sbxgwj",
    "legacy_standing_tv_udotid",
    "legacy_standing_tv_wbkvxr",
    "legacy_steak_ppykkp",
    "legacy_sticky_note_tghqep",
    "legacy_stocking_imdhfp",
    "legacy_stool_miftfy",
    "legacy_stool_mysfnz",
    "legacy_stool_sghekm",
    "legacy_stool_ycfbsd",
    "legacy_straight_chair_amgwaw",
    "legacy_straight_chair_axmhdk",
    "legacy_straight_chair_dmcixv",
    "legacy_straight_chair_dmdipc",
    "legacy_straight_chair_fgoezn",
    "legacy_straight_chair_gxzrim",
    "legacy_straight_chair_haaiau",
    "legacy_straight_chair_hetymd",
    "legacy_straight_chair_kywbxv",
    "legacy_straight_chair_laxufh",
    "legacy_straight_chair_lxmgbs",
    "legacy_straight_chair_mdnhjm",
    "legacy_straight_chair_mgzcic",
    "legacy_straight_chair_myxhad",
    "legacy_straight_chair_osvmes",
    "legacy_straight_chair_psoizi",
    "legacy_straight_chair_rosdkm",
    "legacy_straight_chair_tfdjag",
    "legacy_straight_chair_vkgbbl",
    "legacy_straight_chair_xfhcep",
    "legacy_straight_chair_zhojwx",
    "legacy_straight_pin_ohhsqc",
    "legacy_straw_ovckrp",
    "legacy_straw_qcqvjt",
    "legacy_strawberry_pgguhi",
    "legacy_strawberry_xcnzxh",
    "legacy_sugar_jar_bholak",
    "legacy_sunglass_nxfifs",
    "legacy_sunglass_wdxiwf",
    "legacy_sunscreen_prlrwi",
    "legacy_sushi_akpnxn",
    "legacy_sweater_ekcjci",
    "legacy_sweater_eknmzl",
    "legacy_sweet_corn_dacgvr",
    "legacy_swivel_chair_llckbs",
    "legacy_table_lamp_awfehr",
    "legacy_table_lamp_dkfwyb",
    "legacy_table_lamp_kwkqot",
    "legacy_table_lamp_lyjkje",
    "legacy_table_lamp_ncgcgo",
    "legacy_table_lamp_tggobp",
    "legacy_table_lamp_tnbwvj",
    "legacy_table_lamp_utsqrs",
    "legacy_table_lamp_wslomg",
    "legacy_table_lamp_zpqejt",
    "legacy_tablefork_flexrc",
    "legacy_tablefork_pqrtkc",
    "legacy_tape_budhaz",
    "legacy_tape_fetnry",
    "legacy_tape_gchdhk",
    "legacy_tape_sklkyc",
    "legacy_tape_vpgzne",
    "legacy_tape_yyekns",
    "legacy_tart_borxmv",
    "legacy_tea_bag_kmvcrb",
    "legacy_teapot_foaehs",
    "legacy_thumbtack_qfrphh",
    "legacy_tile_kuombe",
    "legacy_tile_vowkci",
    "legacy_tinsel_ndmqqw",
    "legacy_toaster_kjwqav",
    "legacy_toasting_fork_osrfkc",
    "legacy_toasting_fork_vokznh",
    "legacy_toilet_kfmkbm",
    "legacy_toilet_nqwekw",
    "legacy_toilet_sjjweo",
    "legacy_toilet_vtqdev",
    "legacy_toilet_wusctd",
    "legacy_tomato_altlfz",
    "legacy_tomato_wjreyv",
    "legacy_tongs_rcpjld",
    "legacy_toothpaste_vsclsj",
    "legacy_toothpick_deysav",
    "legacy_towel_rack_crivoa",
    "legacy_towel_rack_kqrmrh",
    "legacy_towel_rack_pqhsry",
    "legacy_toy_acymin",
    "legacy_toy_aihmqy",
    "legacy_toy_cobfpg",
    "legacy_toy_cqeowc",
    "legacy_toy_ecvxmu",
    "legacy_toy_fnueyn",
    "legacy_toy_gdekzd",
    "legacy_toy_gnofgv",
    "legacy_toy_gqspnb",
    "legacy_toy_gyrsew",
    "legacy_toy_issvzv",
    "legacy_toy_jddrck",
    "legacy_toy_jwjrza",
    "legacy_toy_krmxjk",
    "legacy_toy_lfxygp",
    "legacy_toy_nncqfn",
    "legacy_toy_orunry",
    "legacy_toy_tjchdg",
    "legacy_toy_txgpxx",
    "legacy_toy_vcmcoi",
    "legacy_toy_wvpqbf",
    "legacy_toy_zuntus",
    "legacy_trash_can_aefcem",
    "legacy_trash_can_eahqyq",
    "legacy_trash_can_glzckq",
    "legacy_trash_can_gsgutn",
    "legacy_trash_can_hqdnjz",
    "legacy_trash_can_ifzxzj",
    "legacy_trash_can_leazin",
    "legacy_trash_can_rteihy",
    "legacy_trash_can_wklill",
    "legacy_trash_can_xkqkbf",
    "legacy_tray_xzcnjq",
    "legacy_treadmill_ackppx",
    "legacy_treadmill_ahwnhu",
    "legacy_trowel_ematag",
    "legacy_turnip_nnvlrd",
    "legacy_umbrella_cqfbku",
    "legacy_umbrella_zxnjwz",
    "legacy_underwear_uwzqxm",
    "legacy_vidalia_onion_buyxll",
    "legacy_vidalia_onion_ldeuli",
    "legacy_vidalia_onion_tnmqrt",
    "legacy_vidalia_onion_yxwjgn",
    "legacy_video_game_apjpos",
    "legacy_video_game_ceaxsd",
    "legacy_video_game_ckugyi",
    "legacy_video_game_coiafo",
    "legacy_video_game_lfdpse",
    "legacy_video_game_muwcnf",
    "legacy_video_game_ppnzqm",
    "legacy_video_game_pujfzk",
    "legacy_video_game_qsyyql",
    "legacy_video_game_quzjuo",
    "legacy_video_game_rzaxlj",
    "legacy_video_game_veodkq",
    "legacy_video_game_yyvkel",
    "legacy_vinegar_snzyfk",
    "legacy_walker_cmfdmv",
    "legacy_walker_dgewyj",
    "legacy_walker_glrsok",
    "legacy_walker_ndexvs",
    "legacy_walker_scbatq",
    "legacy_walker_txpihh",
    "legacy_walker_xnpimz",
    "legacy_walker_ykjauh",
    "legacy_wall_mounted_tv_gffrzl",
    "legacy_wall_mounted_tv_ggfznh",
    "legacy_wall_mounted_tv_ylvjhb",
    "legacy_wall_socket_eaxxbm",
    "legacy_walnut_nzqier",
    "legacy_walnut_rmwtdh",
    "legacy_watch_ghobzn",
    "legacy_water_emquat",
    "legacy_watermelon_slucoe",
    "legacy_watermelon_zgmaqe",
    "legacy_whiteboard_bqqmtc",
    "legacy_wine_bottle_fzuiwy",
    "legacy_wine_bottle_hnkiog",
    "legacy_wine_bottle_vecadn",
    "legacy_wrapped_gift_wpmksn",
    "legacy_yogurt_kihdsj",
    "legacy_zucchini_dybtwb",
    "legacy_zucchini_ifvmal",
    "legacy_zucchini_udvfaz",
    "lettuce-ak",
    "lighter-no",
    "lighter_fluid-2z",
    "lingerie-gx",
    "lingerie-ov",
    "lint_roller-u6",
    "lip_balm-ma",
    "litter_box-gr",
    "longboard-ew",
    "loofah-5l",
    "lubricant-iz",
    "maple_syrup-is",
    "marker-xh",
    "mask-s8",
    "match-zl",
    "matcha-rv",
    "measuring_cup-7l",
    "measuring_tape-4b",
    "meat_thermometer-nt",
    "meatloaf-55",
    "melon-5a",
    "meringue-sm",
    "mesh_bag-hz",
    "microfiber_cloth-ji",
    "milkshake-zb",
    "miso-un",
    "mistletoe_holly-vr",
    "mixing_bowl-fp",
    "molasses-x9",
    "mortar-v2",
    "mulch-4v",
    "mustard_greens-zy",
    "nachos-pj",
    "name_tag-so",
    "necktie-is",
    "nectarine-id",
    "nickel-qu",
    "noodle-21",
    "notepad-mg",
    "okra-yk",
    "omelet-06",
    "onion-xr",
    "onion_powder-a9",
    "outlet-np",
    "oyster-xp",
    "paint_remover-rb",
    "pancake-7b",
    "pants-fq",
    "paraffin_wax-3l",
    "parchment_paper-ox",
    "parsnip-7h",
    "pastry_brush-h1",
    "pastry_cutter-bx",
    "patina-77",
    "paver-bp",
    "pea_pods-hg",
    "peanut_butter-pa",
    "pearl-r9",
    "pebbles-js",
    "pennant-zu",
    "pepperoni-ca",
    "pesticide-ik",
    "pet_food-nf",
    "pickle-kk",
    "pillowcase-ye",
    "pin-gl",
    "pine_cones-ui",
    "pitcher-xk",
    "pizza_box-vm",
    "pizza_dough-ti",
    "plant_pot-7o",
    "plastic_bag-3p",
    "plastic_wrap-de",
    "plier-8w",
    "plug-jv",
    "plush_toy-de",
    "poker-gh",
    "pole-lx",
    "pork_chop-re",
    "pork_rib-l3",
    "powdered_sugar-id",
    "pump-m2",
    "pumpkin_pie_spice-et",
    "purse-go",
    "pvc_pipe-2a",
    "quail_breast-ia",
    "quail_breast_raw-5i",
    "quail_leg-1u",
    "quartz-l8",
    "rack-cg",
    "racket-fw",
    "radio-jn",
    "rainboots-lf",
    "raincoat-ya",
    "red_wine-kt",
    "retainer-zj",
    "rhubarb-np",
    "rice-ja",
    "rice_cooker-av",
    "roasting_pan-kd",
    "rock-ae",
    "rolling_pin-fl",
    "rose-mz",
    "rug-qp",
    "ruler-es",
    "rum-ve",
    "rutabaga-wq",
    "salmon-vg",
    "salsa-vb",
    "sanitizer-pt",
    "sauce_set-dg",
    "saucer-gw",
    "schnitzel-ia",
    "scrambled_eggs-la",
    "sealant-oq",
    "shaker-nl",
    "shirt-pe",
    "shoe_box-gw",
    "shopping_cart-wo",
    "shortening-vz",
    "shovel-xa",
    "shrimp-oq",
    "shutter-vl",
    "skirt-yq",
    "slow_cooker-ic",
    "smoothie-ee",
    "sneakers-cr",
    "snow_globe-aw",
    "snow_pants-ic",
    "socks-bz",
    "sod-cj",
    "soda-oe",
    "sour_cream-kx",
    "spaghetti-nm",
    "sparkler-wk",
    "spices-pa",
    "sponge-le",
    "spray_bottle-ea",
    "squash-fa",
    "sriracha-bb",
    "stapler-tr",
    "steel_wool",
    "stripping_solution-mx",
    "stroller-he",
    "sunglasses-wo",
    "sweatshirt-kd",
    "sweet_almond_oil-me",
    "swimsuit-hr",
    "syringe-pb",
    "table_lamp-pq",
    "tablet-re",
    "tarp-zs",
    "tassel-ie",
    "teacup-mj",
    "teddy_bear-ir",
    "tennis_ball-zc",
    "tent-md",
    "tequilla-jo",
    "textbook-ag",
    "thermometer-av",
    "thermostat-ob",
    "thread-zl",
    "ticket-et",
    "tights-rh",
    "tire-ks",
    "tong-temp",
    "tortilla-bq",
    "towels-ib",
    "toy_train-vj",
    "trombone-sg",
    "trophy-af",
    "trumpet-gh",
    "tulip-ce",
    "tupperware-un",
    "turtleneck-yh",
    "utility_knife-ba",
    "vase-temp",
    "vest-mq",
    "vodka-ht",
    "waffle-yd",
    "waffle_maker-dr",
    "wallet-ql",
    "water_filter-kl",
    "watering_can-ek",
    "wax-al",
    "weed-dj",
    "white_chocolate-nj",
    "wool_coat-ge",
    "wrapping_paper-jc",
    "wrench-ac",
    "yeast-kr",
}

APPROVED_SCENES = {
    "restaurant_hotel",
}

def main():
    root_path = os.path.abspath(os.path.join(os.path.dirname(__file__), ROOT_PATH))

    objects_path = os.path.join(os.path.dirname(__file__), OBJS_DIR)
    all_object_list = os.listdir(objects_path)
    approved_objects = {} # sorted(set(all_object_list) & APPROVED_OBJS)
    objects = sorted(["objects/" + x for x in approved_objects])
    objects_unfiltered = sorted(["objects/" + x for x in all_object_list])

    scenes_path = os.path.join(os.path.dirname(__file__), SCENES_DIR)
    all_scenes_list = os.listdir(scenes_path)
    approved_scenes = {} # sorted(set(all_scenes_list) & APPROVED_SCENES)
    scenes = sorted(["scenes/" + x for x in approved_scenes]) #
    scenes_unfiltered = sorted(["scenes/" + x for x in all_scenes_list]) #

    combined = objects + scenes
    combined_unfiltered = objects_unfiltered + scenes_unfiltered

    missing_final_scene_paths = set(FINAL_SCENES) - set(approved_scenes)
    assert not missing_final_scene_paths, f"Missing scenes: {missing_final_scene_paths}"
    final_scenes = sorted(["scenes/" + x for x in FINAL_SCENES])

    out_path = os.path.join(os.path.dirname(__file__), OUT_PATH)
    params = {
        "objects": objects,
        "objects_unfiltered": objects_unfiltered,
        "scenes": scenes,
        "scenes_unfiltered": scenes_unfiltered,
        "final_scenes": final_scenes,
        "combined": combined,
        "combined_unfiltered": combined_unfiltered,
        "root_path": root_path}
    with open(out_path, "w") as f:
        yaml.dump(params, f)

    # Now update the # placeholders in deps
    dvc_tmpl_path = os.path.join(os.path.dirname(__file__), DVC_TMPL_PATH)
    with open(dvc_tmpl_path, "r") as f:
        dvc_conf = yaml.load(f, Loader=yaml.SafeLoader)

    for stage in dvc_conf["stages"].values():
        deps_list = None
        if "deps" in stage:
            deps_list = stage["deps"]
        elif "do" in stage and "deps" in stage["do"]:
            deps_list = stage["do"]["deps"]
        else:
            continue

        new_deps_list = []
        for dep in deps_list:
            match = DEP_REGEX.search(dep)
            if match is None:
                new_deps_list.append(dep)
                continue
            
            key = match.group(1)
            assert key in params, f"Unknown placeholder {key}"
            replacements = params[key]
            for replacement in replacements:
                new_deps_list.append(DEP_REGEX.sub(replacement, dep))

        if "deps" in stage:
            stage["deps"] = new_deps_list
        elif "do" in stage and "deps" in stage["do"]:
            stage["do"]["deps"] = new_deps_list

    # Write the DVC file.
    dvc_out_path = os.path.join(os.path.dirname(__file__), DVC_OUT_PATH)
    with open(dvc_out_path, "w") as f:
        yaml.dump(dvc_conf, f)

    print("Params updated successfully.")

if __name__ == "__main__":
    main()