# @package _global_

policy_name: openvla 
log_path: ~/logs/b1k_baselines/OmniGibson/logs/openvla

model:
  _target_: omnigibson.learning.policies.OpenVLA
  robot_type: ${robot.type}
  host: 0.0.0.0
  port: 8777
  text_prompt: pick up the trash
  use_task_info: false
  control_mode: receeding_temporal